web-infra-dev/rstest

packages/core/package.json
packages/core/src/reporter/summary.ts
pnpm-lock.yaml

support print error code frame

feat: support print error code frame

---

.github/workflows/test.yml
scripts/dictionary.txt

- fix lint. https://github.com/web-infra-dev/rstest/actions/runs/14165231629/job/39677174354
- enable `paths-filter` action

chore(ci): fix lint & enable paths-filter

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/core/context.ts
packages/core/src/types/config.ts

Support update snapshot via `update` configuration, and it will update all changed snapshots and delete obsolete ones.

feat: support update snapshot via `update` configuration

---

packages/core/src/api/index.ts
packages/core/src/pool/forks.ts
packages/core/src/pool/index.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/summary.ts
packages/core/src/runner/index.ts
packages/core/src/runner/runner.ts
packages/core/src/types/reporter.ts
packages/core/src/types/testSuite.ts
packages/core/src/worker/index.ts

rename type `TestSummaryResult` to `TestFileResult`.

chore(type): rename TestSummaryResult to TestFileResult

---

packages/core/package.json
packages/core/rslib.config.ts
packages/core/src/config.ts
packages/core/src/core/context.ts
packages/core/src/index.ts
packages/core/src/node.ts
packages/core/src/types/config.ts
packages/core/src/types/reporter.ts
packages/core/src/worker/loadModule.ts
pnpm-lock.yaml
tests/afterAll/index.test.ts
tests/package.json
tests/reporter/fixtures/index.test.ts
tests/reporter/index.test.ts
tests/reporter/package.json
tests/reporter/rstest.config.ts
tests/reporter/rstest.customReporterConfig.ts
tests/reporter/rstest.emptyReporterConfig.ts
tests/scripts/index.ts

Pre-request test feature for https://github.com/web-infra-dev/rstest/pull/63.

feat: support `reporters` in config

---

.gitignore
examples/node/package.json
packages/core/rslib.config.ts
packages/core/src/cli/commands.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts
packages/core/src/env.d.ts
pnpm-lock.yaml
tests/afterAll/index.test.ts
tests/cli/index.test.ts
tests/reporter/index.test.ts
tests/rstest.config.ts
tests/scripts/index.ts
tests/scripts/utils.ts
tests/setup/index.test.ts
tests/snapshot/file.test.ts
tests/watch/fixtures/index.test.ts
tests/watch/fixtures/src/index.ts
tests/watch/index.test.ts
tests/watch/package.json
tests/watch/rstest.config.ts

Support basic watch mode, implement with context dependency.

feat: support basic watch mode

---

packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts

fix: get build time from Rspack stats

---

README.md

Reference https://github.com/web-infra-dev/rstest/issues/85

docs: add roadmap link

---

packages/core/package.json
packages/core/src/pool/index.ts
packages/core/src/reporter/summary.ts
packages/core/src/types/testSuite.ts
packages/core/src/utils/runtime.ts
pnpm-lock.yaml
tests/diff/fixtures/index.test.ts
tests/diff/index.test.ts

support print error diff, powered by [jest-diff](https://www.npmjs.com/package/jest-diff) 🌹 .
diff string:
diff object:

feat: support print diff

---

.github/workflows/lint.yml
.github/workflows/release.yml

Unify action version comments to avoid `renovate` create PR repeat.
https://github.com/web-infra-dev/rstest/pull/91
https://github.com/web-infra-dev/rstest/pull/89

chore(workflow): unify action version comment

---

packages/core/src/reporter/summary.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/util.ts
tests/lifecycle/error.test.ts
tests/lifecycle/fixtures/error/afterAll.test.ts
tests/lifecycle/fixtures/error/afterEach.test.ts
tests/lifecycle/fixtures/error/beforeAll.test.ts
tests/lifecycle/fixtures/error/beforeAllRoot.test.ts
tests/lifecycle/fixtures/error/beforeEach.test.ts
tests/lifecycle/index.test.ts

Enhancing error handling in lifecycle hooks, updating test fixtures, and modifying the reporter to handle specific edge cases.
* Enhanced error handling in `beforeAll`, `beforeEach`, `afterAll`, and `afterEach` hooks to ensure proper test execution and error reporting.

feat: support handle hooks error

---

packages/core/src/cli/commands.ts

chore: update command description

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/expect/test/fixtures/timeout.test.ts
tests/expect/test/index.test.ts

Support test timeout, the default is 5 seconds. should throw timeout error when test timeout.

feat: add test timeout

---

packages/core/src/core/plugins/entry.ts
packages/core/src/core/rsbuild.ts

extract test file watch as rsbuild plugin.

chore: extract test file watch as rsbuild plugin

---

packages/core/src/runtime/runner/runner.ts
packages/core/src/types/testSuite.ts
tests/expect/test/fixtures/soft.test.ts
tests/expect/test/index.test.ts
tests/expect/test/soft.test.ts
tests/setup/fixtures/basic/index.test.ts
tests/setup/fixtures/basic/rstest.setup.ts
tests/spy/index.test.ts

- fix `expect.soft` api
- add more test cases

fix: `expect.soft` api

---

packages/core/src/types/mock.ts

docs(mock): add jsDoc for `mockInstance`

---

.github/pr-labeler.yml

https://github.com/web-infra-dev/rstest/labels

chore: support release label

---

packages/core/package.json

reference: https://github.com/web-infra-dev/rsbuild/pull/5032

fix: update node engine range to >=18.0

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/test-api/chain.test.ts
tests/test-api/edgeCase.test.ts
tests/test-api/fixtures/only.each.test.ts
tests/test-api/fixtures/only.fails.test.ts
tests/test-api/fixtures/onlyInSkip.test.ts

- `test.only.each`
- `test.only.fails`
- `test.skip.each`
- `test.skip.fails`

feat: support chain test api

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/describe/chain.test.ts
tests/describe/fixtures/only.each.test.ts
tests/describe/fixtures/skip.each.test.ts

- `describe.only.each`
- `describe.skip.each`

feat: support chain describe API

---

packages/core/src/pool/index.ts
packages/core/src/reporter/index.ts
packages/core/src/types/reporter.ts

rename `reporter.onConsoleLog` to `reporter.onUserConsoleLog`

chore: rename reporter.onConsoleLog to onUserConsoleLog

---

packages/core/src/reporter/index.ts
packages/core/src/runtime/worker/console.ts
packages/core/src/types/testSuite.ts
tests/log/fixtures/log.test.ts
tests/log/index.test.ts

feat: support proxy more console methods

---

packages/core/src/cli/commands.ts
packages/core/src/cli/prepare.ts
packages/core/src/core/runTests.ts
packages/core/src/pool/index.ts
packages/core/src/types/core.ts
tests/list/fixtures/a.test.ts
tests/list/fixtures/b.test.ts
tests/list/index.test.ts

feat: init rstest list command

---

packages/core/src/cli/commands.ts
packages/core/src/core/index.ts
packages/core/src/core/listTests.ts
packages/core/src/core/runTests.ts
packages/core/src/pool/forks.ts
packages/core/src/pool/index.ts
packages/core/src/runtime/api/index.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/core.ts
packages/core/src/types/worker.ts
tests/list/index.test.ts
tests/scripts/index.ts

feat: support collect & list tests

---

packages/core/src/core/listTests.ts
tests/list/index.test.ts

fix: should list tests correctly with test name filter

---

packages/core/src/core/context.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/statusRenderer.ts
packages/core/src/reporter/windowedRenderer.ts

feat(reporter): support render status

---

packages/core/src/reporter/index.ts
tests/log/fixtures/logSrc.test.ts
tests/log/fixtures/src/index.ts
tests/log/index.test.ts
tests/log/trace.test.ts

should print console trace correctly.

fix: should print console trace correctly

---

packages/core/src/runtime/runner/runner.ts
tests/test-api/extend.depends.test.ts
tests/test-api/extend.extend.test.ts
tests/test-api/extend.test.ts

reverse execution of extend cleanup function.

fix: reverse execution of extend cleanup function

---

packages/core/package.json
website/docs/en/guide/_meta.json
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/guide/_meta.json
website/docs/zh/guide/start/quick-start.mdx

add 'setup environment' chapter.

docs: add 'setup environment' chapter

---

pnpm-lock.yaml
website/package.json
website/rspress.config.ts

Added the `rsbuild-plugin-google-analytics` package to enable Google Analytics support.

chore: set up Google Analytics for site

---

packages/core/src/reporter/summary.ts

fix file not found error when printCodeFrame

fix: file not found error when printCodeFrame

---

packages/core/src/runtime/runner/runtime.ts

chore: optimize test API

---

.github/workflows/preview.yml
packages/core/package.json
packages/core/rslib.config.ts
packages/core/src/core/listTests.ts
packages/core/src/node.ts
pnpm-lock.yaml

fix missing type in preview version

fix(types): missing type in preview version

---

packages/core/package.json
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
pnpm-lock.yaml

https://github.com/web-infra-dev/rsbuild/releases/tag/v1.4.0-beta.0

chore(deps): bump rsbuild 1.4.0-beta

---

packages/core/src/cli/commands.ts
packages/core/src/core/index.ts
packages/core/src/pool/index.ts
packages/core/src/reporter/index.ts
packages/core/src/types/core.ts
packages/core/src/types/reporter.ts
tests/cli/fixtures/error.config.ts
tests/cli/index.test.ts

should print unhandled error correctly, such as invalid pool configuration:

fix: should print unhandled error correctly

---

packages/core/src/core/listTests.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/statusRenderer.ts
packages/core/src/reporter/summary.ts
packages/core/src/utils/testFiles.ts

- only highlight test file name
- omit total files summary when test kinds only one.
before:
after:

chore: simplify test logs

---

packages/core/src/reporter/index.ts
tests/reporter/index.test.ts

enhance: support expand slow test cases

---

tests/snapshot/fail.test.ts
tests/snapshot/file.test.ts

https://github.com/web-infra-dev/rstest/actions/runs/15461876052/job/43524855862

test: fix frequent snapshot cases timeout issues in CI 

---

packages/core/package.json

release: 0.0.1

---

.github/workflows/release.yml

chore(workflow): rename npm token

---

packages/core/src/runtime/worker/loadModule.ts

chore: remove repeat brackets

---

tests/basic/src/meta.ts
tests/basic/test/dynamicImport.test.ts
tests/basic/test/meta.test.ts

enable more meta info test cases.
https://github.com/web-infra-dev/rstest/pull/229

test: enable more meta info cases

---

packages/core/src/config.ts
website/docs/en/config/_meta.json
website/docs/en/config/index.mdx
website/docs/en/config/test/_meta.json
website/docs/en/config/test/exclude.mdx
website/docs/en/config/test/include.mdx
website/docs/zh/config/_meta.json
website/docs/zh/config/index.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/exclude.mdx
website/docs/zh/config/test/include.mdx

docs: add `include` and `exclude` configs

docs: add `include` and `exclude` configs

---

packages/core/package.json

* feat: inject __dirname and __filename of source file path by @fi3ework in https://github.com/web-infra-dev/rstest/pull/229
* feat(core): add "rs" as the alias for "rstest" by @fi3ework in https://github.com/web-infra-dev/rstest/pull/282
* feat: support `jsdom` test by @9aoy in https://github.com/web-infra-dev/rstest/pull/284
* feat: add requireActual function declaration by @fi3ework in https://github.com/web-infra-dev/rstest/pull/288
* feat: support mock timers by @9aoy in https://github.com/web-infra-dev/rstest/pull/285
* fix: wrong `main` & `types` fileds value by @9aoy in https://github.com/web-infra-dev/rstest/pull/276
* fix:remove inaccurate external path matching by @9aoy in https://github.com/web-infra-dev/rstest/pull/289
* fix: interop `default` in jsdom test environment by …

release: 0.0.2

---

website/docs/en/config/test/_meta.json
website/docs/en/config/test/includeSource.mdx
website/docs/en/guide/start/quick-start.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/includeSource.mdx
website/docs/zh/guide/start/quick-start.mdx

docs: add `includeSource` configuration

docs: add `includeSource` configuration

---

packages/core/src/core/rsbuild.ts

merge debug outputs variable to `DEBUG=rstest`

chore: merge debug outputs variable to `DEBUG=rstest`

---

packages/core/src/utils/testFiles.ts
packages/core/tests/utils/testFiles.test.ts

Format test entry names to make output file structure clearer.

chore: format test entry names

---

scripts/dictionary.txt
website/docs/en/config/test/_meta.json
website/docs/en/config/test/testEnvironment.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/testEnvironment.mdx

add `testEnvironment` configuration document.

docs: add `testEnvironment` configuration

---

website/docs/en/config/build/_meta.json
website/docs/en/config/build/source.mdx
website/docs/zh/config/build/_meta.json
website/docs/zh/config/build/source.mdx

add source configurations doc.

docs: add source configurations

---

website/docs/en/config/build/_meta.json
website/docs/en/config/build/dev.mdx
website/docs/en/config/build/performance.mdx
website/docs/en/config/build/resolve.mdx
website/docs/en/config/build/tools.mdx
website/docs/zh/config/build/_meta.json
website/docs/zh/config/build/dev.mdx
website/docs/zh/config/build/performance.mdx
website/docs/zh/config/build/resolve.mdx
website/docs/zh/config/build/tools.mdx

docs: add more build configs

---

packages/core/src/runtime/api/spy.ts
packages/core/src/types/mock.ts
tests/spy/index.test.ts

Code is ported from https://redirect.github.com/vitest-dev/vitest/pull/6181. Thanks for the great work.

fix(spy): fix mockImplementation for function overload and unions

---

packages/core/src/runtime/api/snapshot.ts
website/docs/en/api/_meta.json
website/docs/en/api/test-api/test.mdx
website/docs/zh/api/_meta.json
website/docs/zh/api/test-api/test.mdx

docs: add test API

---

packages/core/src/core/listTests.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts
website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/debug-mode.mdx
website/docs/zh/guide/advanced/_meta.json
website/docs/zh/guide/advanced/debug-mode.mdx

support write rstest config to disk in debug mode.

enhance: support inspect rstest config

---

website/docs/en/api/rstest/_meta.json
website/docs/en/api/rstest/mockFunctions.mdx
website/docs/en/api/rstest/mockInstance.mdx
website/docs/en/config/test/_meta.json
website/docs/en/config/test/clearMocks.mdx
website/docs/en/config/test/resetMocks.mdx
website/docs/en/config/test/restoreMocks.mdx
website/docs/zh/api/rstest/_meta.json
website/docs/zh/api/rstest/mockFunctions.mdx
website/docs/zh/api/rstest/mockInstance.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/clearMocks.mdx
website/docs/zh/config/test/resetMocks.mdx
website/docs/zh/config/test/restoreMocks.mdx

docs: add mock configs and `MockInstance` API.

docs: add mock configs and `MockInstance` API 

---

scripts/dictionary.txt
website/docs/en/api/rstest/_meta.json
website/docs/en/api/rstest/mockFunctions.mdx
website/docs/en/api/rstest/utilities.mdx
website/docs/en/api/test-api/_meta.json
website/docs/en/config/test/_meta.json
website/docs/en/config/test/unstubEnvs.mdx
website/docs/en/config/test/unstubGlobals.mdx
website/docs/zh/api/rstest/_meta.json
website/docs/zh/api/rstest/mockFunctions.mdx
website/docs/zh/api/rstest/utilities.mdx
website/docs/zh/api/test-api/_meta.json
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/unstubEnvs.mdx
website/docs/zh/config/test/unstubGlobals.mdx

docs: add some rstest utilities API.

docs: add some rstest utilities API

---

packages/core/package.json

* feat: more mock api by @fi3ework in https://github.com/web-infra-dev/rstest/pull/290
* perf: add pre-filter for css by @9aoy in https://github.com/web-infra-dev/rstest/pull/352
* fix: should run tests correctly when isolate false by @9aoy in https://github.com/web-infra-dev/rstest/pull/343
* fix(mock): resetModules should not clear mock by @fi3ework in https://github.com/web-infra-dev/rstest/pull/349
* fix: enable --experimental-detect-module by default for node20 by @fi3ework in https://github.com/web-infra-dev/rstest/pull/351
* docs: add more configuration items by @9aoy in https://github.com/web-infra-dev/rstest/pull/345
* docs: add mock configs and `MockInstance` API  by @9aoy in https://github.com/web-infra-dev/rstest/pull/346
* docs: add some rstest utilities API by @9aoy in …

release: 0.0.5

---

tests/dom/css.test.ts
tests/dom/handledError.test.ts
tests/dom/index.test.ts
tests/dom/unhandledError.test.ts
tests/dom/utils.ts

test: refactor dom test run logic

---

packages/core/src/reporter/index.ts
website/docs/en/config/test/retry.mdx
website/docs/zh/config/test/retry.mdx

chore: polish retry log & docs

---

package.json

exclude useless tests build.
https://github.com/web-infra-dev/rstest/actions/runs/16071118348/job/45355787875

chore: exclude useless tests build

---

.github/eco-ci-result/action.yml
.github/workflows/ecosystem-ci.yml

add ecosystem CI workflow
https://github.com/rspack-contrib/rstest-ecosystem-ci

chore(workflow): add ecosystem CI

---

website/docs/en/api/rstest/mockFunctions.mdx
website/docs/en/api/test-api/_meta.json
website/docs/en/api/test-api/expect.mdx
website/docs/zh/api/rstest/mockFunctions.mdx
website/docs/zh/api/test-api/_meta.json
website/docs/zh/api/test-api/expect.mdx

docs: add expect API

---

packages/core/package.json

* feat: export Mock type by @chenjiahan in https://github.com/web-infra-dev/rstest/pull/372
* feat: support using package name as `setupFiles` value by @9aoy in https://github.com/web-infra-dev/rstest/pull/377
* fix: unexpected resolution of vue to `vue.cjs.prod.js` when `NODE_ENV=test` by @9aoy in https://github.com/web-infra-dev/rstest/pull/374
* docs: add expect API by @9aoy in https://github.com/web-infra-dev/rstest/pull/370
* docs: polish up by @fi3ework in https://github.com/web-infra-dev/rstest/pull/375
* chore(deps): update all patch dependencies by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/366
* chore: exclude useless tests build by @9aoy in https://github.com/web-infra-dev/rstest/pull/367
* chore(workflow): add ecosystem CI by @9aoy in …

release: 0.0.7

---

packages/core/package.json

* feat: support bundle `node_modules` in node environment by @9aoy in https://github.com/web-infra-dev/rstest/pull/394
* fix: should keep `require.resolve` expressions by @9aoy in https://github.com/web-infra-dev/rstest/pull/395
* docs(api): mock modules by @fi3ework in https://github.com/web-infra-dev/rstest/pull/397
* chore(workflow): test in node.js v24 by @9aoy in https://github.com/web-infra-dev/rstest/pull/392
* chore(deps): update all patch dependencies by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/400
* chore(deps): update dependency birpc to v2.5.0 by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/401
* chore(deps): update dependency nx to ^21.3.1 by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/402
**Full Changelog**: …

release: 0.0.9

---

packages/core/src/runtime/worker/index.ts
tests/dom/fixtures/test/uncaughtException.test.ts
tests/dom/uncaughtException.test.ts
tests/scripts/index.ts

improve error handling for unhandledRejection exception.
before:
after:

fix: improve error handling for unhandledRejection exception

---

packages/core/package.json

* feat: support Github Actions Reporter by @9aoy in https://github.com/web-infra-dev/rstest/pull/429
* feat: support VerboseReporter by @9aoy in https://github.com/web-infra-dev/rstest/pull/425
* fix: should show `module not found` error codeFrame correctly by @9aoy in https://github.com/web-infra-dev/rstest/pull/427
* fix: improve error handling for unhandledRejection exception by @9aoy in https://github.com/web-infra-dev/rstest/pull/428
* docs: add cli options example by @9aoy in https://github.com/web-infra-dev/rstest/pull/426
* chore: add watch tip for watch mode by @9aoy in https://github.com/web-infra-dev/rstest/pull/421
* chore(deps): update dependency memfs to ^4.28.0 by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/431
* chore(deps): update all patch dependencies …

release: 0.1.0

---

packages/core/src/runtime/worker/index.ts
tests/dom/handledError.test.ts
tests/dom/utils.ts

should throw error when unknown environment.

fix: should throw error when unknown environment

---

packages/core/licensePlugin.ts
packages/core/package.json

* perf: prebundle runtime dependencies by @9aoy in https://github.com/web-infra-dev/rstest/pull/436
* fix: should throw error when unknown environment by @9aoy in https://github.com/web-infra-dev/rstest/pull/439
* fix: add original license and copyrights for the referenced code by @9aoy in https://github.com/web-infra-dev/rstest/pull/438
* fix: shim `require` in rstest bundle by @9aoy in https://github.com/web-infra-dev/rstest/pull/440
* docs: add `--reporter` option by @9aoy in https://github.com/web-infra-dev/rstest/pull/434
* docs: update config overview UI by @9aoy in https://github.com/web-infra-dev/rstest/pull/435
* docs: fix `@sinonjs/fake-timers` link by @9aoy in https://github.com/web-infra-dev/rstest/pull/441
* chore(workflow): enable npm trusted publishing by @chenjiahan in …

release: 0.1.1

---

website/docs/en/api/rstest/fakeTimers.mdx
website/docs/en/api/rstest/mockFunctions.mdx
website/docs/en/api/rstest/utilities.mdx
website/docs/zh/api/rstest/fakeTimers.mdx
website/docs/zh/api/rstest/mockFunctions.mdx
website/docs/zh/api/rstest/utilities.mdx

add alias for rstest utility API.

docs: add alias for rstest utility API

---

packages/core/package.json

* refactor!: enable run mode by default when run `rstest` command by @9aoy in https://github.com/web-infra-dev/rstest/pull/448
* fix: use `inline-source-map` when debugger by @9aoy in https://github.com/web-infra-dev/rstest/pull/445
* docs: add alias for rstest utility API by @9aoy in https://github.com/web-infra-dev/rstest/pull/447
* docs: add note for `describe.skip` by @9aoy in https://github.com/web-infra-dev/rstest/pull/446
**Full Changelog**: https://github.com/web-infra-dev/rstest/compare/v0.1.1...v0.1.2

release: 0.1.2

---

README.md
website/docs/en/guide/start/index.mdx

Fix a mistake in https://github.com/web-infra-dev/rstest/pull/451

docs: remove duplicate Rstack description sections

---

packages/core/src/core/cliShortcuts.ts
packages/core/src/core/listTests.ts
packages/core/src/core/runTests.ts
packages/core/src/pool/index.ts

feat: support update snapshot via `u` shortcut

---

packages/core/src/core/runTests.ts
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

docs: add `CLI shortcuts` section

---

packages/core/package.json

* feat: init cli shortcut by @9aoy in https://github.com/web-infra-dev/rstest/pull/453
* feat: support rerun all tests via `a` CLI shortcut by @9aoy in https://github.com/web-infra-dev/rstest/pull/454
* feat: support update snapshot via `u` shortcut by @9aoy in https://github.com/web-infra-dev/rstest/pull/455
* feat: support rerun failed tests via `f` shortcut by @9aoy in https://github.com/web-infra-dev/rstest/pull/456
* docs: add Rslint and version badges to Rstack tools table by @chenjiahan in https://github.com/web-infra-dev/rstest/pull/451
* docs: remove duplicate Rstack description sections by @chenjiahan in https://github.com/web-infra-dev/rstest/pull/452
* docs: add `CLI shortcuts` section by @9aoy in https://github.com/web-infra-dev/rstest/pull/458
* chore: integrate Rslint for …

release: 0.1.3

---

packages/core/src/core/cliShortcuts.ts
packages/core/src/core/listTests.ts
packages/core/src/core/runTests.ts
packages/core/src/pool/index.ts
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

support filter test name regex pattern via `t` shortcut.

feat: support filter test name regex pattern via `t` shortcut

---

package.json
packages/core/package.json

update minimum Node.js version to 18.12.0.
https://github.com/web-infra-dev/rsbuild/pull/5786

feat!: update minimum Node.js version to 18.12.0

---

packages/core/src/core/runTests.ts

fix default worker counts when calc by entry counts.

fix(perf): default worker counts

---

packages/core/package.json

* fix(perf): default worker counts by @9aoy in https://github.com/web-infra-dev/rstest/pull/480
**Full Changelog**: https://github.com/web-infra-dev/rstest/compare/v0.2.0...v0.2.1

release: 0.2.1

---

packages/core/src/core/cliShortcuts.ts

chore: format cli shortcuts output

---

e2e/watch/shortcuts.test.ts

test: add retry for shortcuts case

---

website/docs/en/api/test-api/describe.mdx
website/docs/en/api/test-api/test.mdx

add chainable modifiers examples for `describe` and `test` API.

docs: add chainable modifiers examples

---

e2e/expect/test/index.test.ts

fix unawaited promise in tests.

test: fix unawaited promise in tests

---

e2e/projects/fixtures/packages/client/test/index.test.ts
packages/core/src/core/plugins/basic.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
packages/core/tests/core/rsbuild.test.ts

should avoid outputs conflict in projects.

fix: should avoid outputs conflict in projects

---

e2e/watch/index.test.ts
packages/core/src/core/runTests.ts

update `No test files are re-run`  to`No test files need re-run`

chore: update no rerun log

---

website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/debugging.mdx
website/docs/zh/guide/advanced/_meta.json
website/docs/zh/guide/advanced/debugging.mdx

add `debugging in VS Code` chapter.

docs: add `debugging in VS Code`

---

packages/core/package.json

* feat: add JUnit reporter by @9aoy in https://github.com/web-infra-dev/rstest/pull/528
* docs: update test projects by @9aoy in https://github.com/web-infra-dev/rstest/pull/527
* docs: add `debugging in VS Code` by @9aoy in https://github.com/web-infra-dev/rstest/pull/530
* docs: display llms UI by @9aoy in https://github.com/web-infra-dev/rstest/pull/533
* docs: add configure rsbuild / rspack by @9aoy in https://github.com/web-infra-dev/rstest/pull/532
* type: export `ProjectConfig` by @9aoy in https://github.com/web-infra-dev/rstest/pull/526
* chore: support print full error stack in debug mode by @9aoy in https://github.com/web-infra-dev/rstest/pull/525
* chore: support output projects normalizedConfig in debug mode by @9aoy in https://github.com/web-infra-dev/rstest/pull/531
**Full …

release: 0.3.2

---

e2e/projects/fixtures/packages/node/test/index.test.ts
e2e/projects/fixtures/packages/node/tsconfig.json
e2e/tsconfig.json
packages/core/src/core/plugins/basic.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/rstest.ts
packages/core/src/utils/constants.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
packages/core/tests/core/rsbuild.test.ts

resolve project's tsconfig path correctly.
fix: https://github.com/web-infra-dev/rstest/issues/539

fix: resolve project's tsconfig path correctly

---

packages/core/package.json

* fix: resolve project's tsconfig path correctly by @9aoy in https://github.com/web-infra-dev/rstest/pull/540
* fix: support import rstest in `node_modules` by @9aoy in https://github.com/web-infra-dev/rstest/pull/547
* fix: add `rs` to global API by @9aoy in https://github.com/web-infra-dev/rstest/pull/551
* fix: add `onTestFinished` / `onTestFailed` to global APIs by @9aoy in https://github.com/web-infra-dev/rstest/pull/552
* docs: bump Rspress to fix local search by @fi3ework in https://github.com/web-infra-dev/rstest/pull/542
* docs: add features chapter by @9aoy in https://github.com/web-infra-dev/rstest/pull/534
* docs: use Algolia search by @fi3ework in https://github.com/web-infra-dev/rstest/pull/541
* chore: check dependency installed by @9aoy in …

release: 0.3.3

---

e2e/scripts/index.ts
e2e/test-coverage/fixtures/rstest.thresholds.config.ts
e2e/test-coverage/index.test.ts
packages/core/src/core/runTests.ts
packages/core/src/coverage/checkThresholds.ts
packages/core/src/types/coverage.ts

support check coverage thresholds.

feat: support check coverage thresholds

---

e2e/test-coverage/index.test.ts
packages/coverage-istanbul/package.json
pnpm-lock.yaml

bump swc-plugin-coverage-instrument.
https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/277

chore(deps): bump swc-plugin-coverage-instrument

---

AGENTS.md

chore: add AGENTS.md

---

website/docs/en/config/test/coverage.mdx
website/docs/en/guide/start/features.mdx
website/docs/zh/config/test/coverage.mdx
website/docs/zh/guide/start/features.mdx

docs: polish coverage doc

---

packages/coverage-istanbul/README.md
packages/coverage-istanbul/package.json

update `@rstest/coverage-istanbul` readme.

docs: update `@rstest/coverage-istanbul` readme

---

website/docs/en/guide/migration/jest.mdx
website/docs/zh/guide/migration/jest.mdx

update jest configuration mappings.

docs: update jest configuration mappings

---

packages/core/package.json
packages/coverage-istanbul/package.json

* docs: update `@rstest/coverage-istanbul` readme by @9aoy in https://github.com/web-infra-dev/rstest/pull/572
* docs: add `Migrating from Jest` chapter by @9aoy in https://github.com/web-infra-dev/rstest/pull/574
* docs: polish expect api by @9aoy in https://github.com/web-infra-dev/rstest/pull/576
* docs: update jest configuration mappings by @9aoy in https://github.com/web-infra-dev/rstest/pull/579
* chore: enhance error logs of loading coverage plugin failed by @Timeless0911 in https://github.com/web-infra-dev/rstest/pull/573
* chore(type): make `pool.type` optional by @9aoy in https://github.com/web-infra-dev/rstest/pull/575
* @Timeless0911 made their first contribution in https://github.com/web-infra-dev/rstest/pull/573
**Full Changelog**: …

release: 0.4.1

---

website/docs/en/config/test/coverage.mdx
website/docs/zh/config/test/coverage.mdx

docs: update `coverage.include`

---

packages/core/package.json

* feat(coverage): support `reportOnFailure` option by @9aoy in https://github.com/web-infra-dev/rstest/pull/597
* feat: support `snapshotFormat` option by @9aoy in https://github.com/web-infra-dev/rstest/pull/609
* fix: update node builtin modules by @9aoy in https://github.com/web-infra-dev/rstest/pull/604
* docs: update jest api alternative by @9aoy in https://github.com/web-infra-dev/rstest/pull/603
* docs: introduce beforeEach / beforeAll returns by @9aoy in https://github.com/web-infra-dev/rstest/pull/607
* test: fix unstable coverage tests by @9aoy in https://github.com/web-infra-dev/rstest/pull/596
* chore(deps): update actions/setup-node action to v5 by @renovate[bot] in https://github.com/web-infra-dev/rstest/pull/600
* chore(deps): update dependency istanbul-lib-instrument to v6 …

release: 0.5.1
