web-infra-dev/rstest

README.md
packages/core/package.json
packages/core/src/api/expect.ts
packages/core/src/api/index.ts
packages/core/src/api/poll.ts
packages/core/src/api/public.ts
packages/core/src/api/snapshot.ts
packages/core/src/core/context.ts
packages/core/src/pool/index.ts
packages/core/src/runner/index.ts
packages/core/src/runner/runner.ts
packages/core/src/runner/runtime.ts
packages/core/src/types/core.ts
packages/core/src/types/global.ts
packages/core/src/types/testSuite.ts
packages/core/src/types/worker.ts
packages/core/src/worker/index.ts
pnpm-lock.yaml
tests/snapshot/__snapshots__/index.test.ts.snap
tests/snapshot/index.test.ts

Integrate snapshot API, the core snapshot API is provided by `@vitest/snapshot` ❤️ .
https://www.npmjs.com/package/@vitest/snapshot
```ts
it('test toMatchSnapshot API', () => {
expect('hello world').toMatchSnapshot();
});
```

feat: integrate snapshot API

---

packages/core/src/api/public.ts
packages/core/src/index.ts
packages/core/src/runner/index.ts
packages/core/src/runner/runner.ts
packages/core/src/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
pnpm-lock.yaml
scripts/dictionary.txt
tests/afterAll/fixtures/index.test.ts
tests/afterAll/index.test.ts
tests/afterAll/package.json
tests/afterAll/rstest.config.ts
tests/package.json
tests/rstest.config.ts
tests/scripts/index.ts

Pre-request test functionality for https://github.com/web-infra-dev/rstest/pull/63.
- will adding `beforeAll` after this PR got merged.
- using CLI util to run Rstest in order to get the stdout in sub process to ensure the `afterAll` executed in correct order.

feat: support afterAll

---

packages/core/src/core/runTests.ts
packages/core/src/pool/index.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/summary.ts
packages/core/src/runner/runner.ts
packages/core/src/types/reporter.ts
packages/core/src/types/testSuite.ts
packages/core/src/utils/helper.ts

Support print snapshot summary log.
This feature is modified based on `Vitest` renderSnapshotSummary method. ❤️ 
https://github.com/vitest-dev/vitest/blob/e8ce94cfb5520a8b69f9071cc5638a53129130d6/packages/vitest/src/node/reporters/renderers/utils.ts#L67

feat: support print snapshot summary log

---

packages/core/src/types/api.ts
packages/core/src/types/global.ts

`RstestExpect` is reference from `ExpectStatic` type, and we update the `ExpectStatic` type by declaring `@vitest/expect` module.
https://github.com/web-infra-dev/rstest/blob/538ce2243d1f292d5e9e22d32087caa96e60c1e0/packages/core/src/types/global.ts#L25-L43

chore: simplify rstest expect type

---

packages/core/src/runner/index.ts
packages/core/src/runner/runtime.ts
packages/core/tests/runner/runtime.test.ts
tests/isolate/test/index.test.ts
tests/isolate/test/index1.test.ts
tests/runner/test/async.test.ts
tests/runner/test/fixtures/async.test.ts
tests/scripts/utils.ts

Support register **async** suite. BTW, If you have some preparations that need to be executed before testing, it is recommended to use `beforeEach` / `beforeAll`.
```ts
describe('Test Async Suite', async () => {
// do something async...
await new Promise<void>((resolve) => {
setTimeout(() => {
resolve();
}, 100);
});
it('should add two numbers correctly', () => {
expect(1 + 1).toBe(2);
});
});
```

feat: support register async suite

---

packages/core/src/api/snapshot.ts
packages/core/src/config.ts
packages/core/src/constants.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/summary.ts
packages/core/src/runner/runner.ts
packages/core/src/runner/runtime.ts
packages/core/src/types/testSuite.ts
packages/core/src/utils/constants.ts
packages/core/src/utils/helper.ts
packages/core/src/utils/index.ts
packages/core/src/worker/index.ts
packages/core/tests/runner/runtime.test.ts
tests/afterAll/index.test.ts
tests/snapshot/__snapshots__/file.test.ts.snap
tests/snapshot/file.test.ts
tests/snapshot/fixtures/index.test.ts

Omit  rstest `_internal_root_suite` name when task name outputs.
before:
after:

enhance: optimize task name output

---

.github/workflows/test.yml

Support run multiple node versions in e2e tests. Compared with UT, Rstest e2e should test node version compatibility.

chore(workflow): run multiple node versions in e2e tests

---

packages/core/src/runner/runner.ts
packages/core/src/runner/runtime.ts
packages/core/src/types/testSuite.ts
packages/core/tests/runner/runner.test.ts
tests/lifecycle/fixtures/skip.test.ts
tests/lifecycle/index.test.ts

fix: should not run hooks when no test case execution.
Add a new `runMode` property to manage the execution state  (`run`, `skip`, `todo`) of test cases and test suites, and sets the runMode of the test suite based on the runMode of its tests.
```ts
describe('level A', () => {
beforeAll(() => {
console.log('[beforeAll] should not run');
});
it.skip('it in level A', () => {
expect(2 + 2).toBe(4);
});
afterAll(() => {
console.log('[afterAll] should not run');
});
});
```

fix: should not run hooks when no test case execution

---

packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/lifecycle/fixtures/timeout.test.ts
tests/lifecycle/timeout.test.ts

Support hooks timeout, the default is 5 seconds. should throw timeout error when hook timeout.
* Added the `wrapTimeout` function to handle hook timeouts and modified the `RunnerRuntime` class to use this function in `beforeAll`, `afterAll`, `beforeEach`, and `afterEach` methods. 
* Updated the `RunnerAPI` type to support optional timeout parameters for `beforeAll`, `afterAll`, `beforeEach`, and `afterEach` methods.

feat: support hooks timeout

---

packages/core/src/public.ts
packages/core/src/runtime/api/expect.ts
packages/core/src/runtime/api/index.ts
packages/core/src/runtime/api/poll.ts
packages/core/src/runtime/api/public.ts
packages/core/src/runtime/api/snapshot.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/worker/index.ts

moving files from `api` to `runtime/api`.

chore: move `api/` into `runtime/`

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/describe/fixtures/skip.test.ts
tests/describe/fixtures/todo.test.ts
tests/describe/index.test.ts

Use `describe.todo` to stub suites to be implemented later. 
```ts
describe.todo('unimplemented suite', () => {
test('todo', () => {
// ......
})
})
```
Use `describe.skip` in a suite to avoid running a particular describe block.
```ts
describe.skip('skipped suite', () => {
test('skip', () => {
// Suite skipped
})
})
```

feat: support describe skip & todo

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/expect/test/fixtures/undefined.test.ts
tests/expect/test/index.test.ts

allow test function undefined.
```ts
it('should passed');
it.skip('should skip');
it.todo('should todo');
it.fails('should failed');
```

feat: allow test function undefined

---

packages/core/src/cli/commands.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/task.ts
packages/core/src/types/config.ts
packages/core/src/types/testSuite.ts
packages/core/src/utils/helper.ts
packages/core/tests/runner/runner.test.ts
tests/filter/fixtures/testNamePattern.test.ts
tests/filter/testNamePattern.test.ts

support filter by `testNamePattern`, will run only tests with a name that matches the regex.
without filter:
with filter `B`:

feat: support filter by testNamePattern

---

packages/core/src/pool/index.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/utils/helper.ts
tests/filter/fixtures/testNamePattern.config.ts
tests/filter/testNamePattern.test.ts

Some special types that do not support passing into the pool, eg. RegExp. we need serialize them when passing into the pool.

feat: support testNamePattern RegExp

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/config.ts
tests/expect/test/index.test.ts

`testTimeout` configuration is used to set default timeout of a test.
```ts
testTimeout: 10_000,
});
```

feat: support `testTimeout` configuration

---

packages/core/src/runtime/runner/runner.ts
packages/core/src/types/testSuite.ts
tests/lifecycle/fixtures/beforeAll.test.ts
tests/setup/fixtures/basic/rstest.setup.ts

support get test file path via `beforeAll` / `afterAll` context.
```ts
beforeAll((ctx) => {
console.log('ctx', ctx.filepath);
});
```

feat: support get test file path via `beforeAll` context

---

packages/core/src/runtime/util.ts
tests/expect/test/edgeCase.test.ts
tests/expect/test/fixtures/error.test.ts
tests/expect/test/index.test.ts

unexpected rpc error about `result.expected`

fix: unexpected rpc error about result.expected

---

README.md
packages/core/README.md

Add the Rstest banner image to README files:

docs: add banner to README

---

packages/core/src/core/plugins/ignoreResolveError.ts
packages/core/src/core/rsbuild.ts
tests/expect/test/edgeCase.test.ts
tests/expect/test/fixtures/moduleNotFound.test.ts

Some `module not found` errors are as expected, so we need to ignore these errors at build time and throw errors at runtime if necessary.

fix: `module not found` errors should be silent at build

---

packages/core/src/runtime/api/spy.ts
packages/core/src/types/mock.ts
tests/spy/index.test.ts

support `mockImplementation`.
- `mockImplementation`: Accepts a function that should be used as the implementation of the mock. 
- `mockImplementationOnce`: Accepts a function that will be used as an implementation of the mock for one call to the mocked function. 
- `getMockImplementation`: Returns current mock implementation.
```ts
const sayHi = rstest.fn().mockImplementation((name: string) => `hi ${name}`;).mockImplementationOnce(() => 'hi')
expect(sayHi('bob')).toBe('hi');
expect(sayHi('bob')).toBe('hi bob');
```

feat: support `mockImplementation`

---

packages/core/globals.d.ts
packages/core/src/utils/constants.ts
pnpm-lock.yaml
tests/globals/fixtures/index.test.ts
tests/globals/fixtures/package.json
tests/globals/fixtures/tsconfig.json
tests/globals/index.test.ts

* Added `rstest` to global API
* Added `rstest` / `beforeAll` / `afterAll`  / `beforeEach`  / `afterEach` to global type

fix: update global api

---

packages/core/src/runtime/api/spy.ts
packages/core/src/types/mock.ts
tests/spy/fixtures/withImplementation.test.ts
tests/spy/withImplementation.test.ts

- `withImplementation`: Accepts a function which should be temporarily used as the implementation of the mock while the callback is being executed.
```ts
test('test', () => {
const mock = rstest.fn(() => 'outside callback');
mock.withImplementation(
() => 'inside callback',
() => {
mock(); // 'inside callback'
},
);
mock(); // 'outside callback'
});
```

feat: support mock `withImplementation`

---

packages/core/src/runtime/api/spy.ts
packages/core/src/types/mock.ts
tests/spy/index.test.ts

- `mockReturnValue`: Accepts a value that will be returned whenever the mock function is called.
- `mockReturnValueOnce`: Accepts a value that will be returned for one call to the mock function. 
- `mockResolvedValue`: Accepts a value that will be resolved when the async function is called. 
- `mockResolvedValueOnce`: Accepts a value that will be resolved during the next function call. 
- `mockRejectedValue`: Accepts an error that will be rejected when async function is called.
- `mockRejectedValueOnce`: Accepts a value that will be rejected during the next function call. 
- `mockReturnThis`: Accepts a value that will be returned whenever the mock function is called.
```ts
const sayHi = rstest.fn();
sayHi.mockReturnValue('hi').mockReturnValueOnce('hello');
expect(sayHi()).toBe('hello'); …
```

feat: support mock returns

---

packages/core/src/runtime/api/spy.ts
packages/core/src/runtime/util.ts
packages/core/src/types/mock.ts
tests/diff/index.test.ts
tests/spy/index.test.ts
tests/spy/invocationCallOrder.test.ts

* Added `lastCall`, `instances`, `contexts`, `settledResults` and `invocationCallOrder` properties to track detailed mock call information.
* Fixed the order of arguments in the `diff` function for error formatting, ensuring correct expected/actual comparison.

feat: support read mock context

---

packages/core/src/runtime/api/spy.ts
packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
tests/spy/spyOn.test.ts

Support create a spy on a method of an object via   `rstest.spyOn`.
```ts
const hi = {
sayHi:  () => 'hi',
};
const spy = rstest.spyOn(hi, 'sayHi');
spy.mockImplementation(() => 'hello');
expect(hi.sayHi()).toBe('hello');
```

feat: support `rstest.spyOn`

---

packages/core/src/runtime/api/spy.ts
packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
tests/spy/clearAllMocks.test.ts

- `clearAllMocks`: Calls `.mockClear()` on all spies.
- `resetAllMocks`: Calls `.mockReset()` on all spies.
- `restoreAllMocks`: Calls `.mockRestore()` on all spies.
```ts
describe('clearAllMocks', () => {
const sayHi = rstest.fn();
afterEach(() => {
rstest.clearAllMocks();
});
it('spy', () => {
sayHi.mockImplementation(() => 'hi');
expect(sayHi('bob')).toBe('hi');
expect(sayHi).toHaveBeenCalledTimes(1);
});
it('spy - 1', () => {
sayHi.mockImplementation(() => 'hello');
expect(sayHi('bob')).toBe('hello');
expect(sayHi).toHaveBeenCalledTimes(1);
});
});
```

feat: support clearAllMocks / resetAllMocks / restoreAllMocks

---

packages/core/src/runtime/api/spy.ts
packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
tests/spy/index.test.ts
tests/spy/spyOn.test.ts

- `isMockFunction`: Determines if the given function is a mocked function.
```ts
const sayHi = rstest.fn();
expect(rstest.isMockFunction(sayHi)).toBeTruthy();
expect(rstest.isMockFunction(() => {})).toBeFalsy();
```

feat: support `rstest.isMockFunction`

---

packages/core/src/runtime/api/snapshot.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/testSuite.ts
tests/snapshot/fixtures/inlineSnapshot.each.test.ts
tests/snapshot/index.test.ts

should throw error when use `toMatchInlineSnapshot` in `test.each`

fix: should throw error when use `toMatchInlineSnapshot` in `test.each`

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/describe/each.test.ts
tests/describe/fixtures/each.test.ts
tests/snapshot/index.test.ts

Support `describe.each` API:
```ts
describe.each([
{ a: 1, b: 1, expected: 2 },
{ a: 1, b: 2, expected: 3 },
{ a: 2, b: 1, expected: 3 },
])('add two numbers correctly', ({ a, b, expected }) => {
it(`should return ${expected}`, () => {
expect(a + b).toBe(expected);
});
});
```

feat: support `describe.each` API

---

tests/scripts/utils.ts
tests/snapshot/file.test.ts

use `expectFile` instead of `waitFile`

test: use `expectFile` instead of `waitFile`

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/runtime/util.ts
packages/core/src/types/api.ts
tests/describe/each.test.ts
tests/describe/fixtures/each.test.ts
tests/runner/test/async.test.ts
tests/scripts/utils.ts
tests/test-api/each.test.ts
tests/test-api/fixtures/each.test.ts

Support array type cases in  test `each` API.
```ts
it.each([
[2, 1, 3],
[2, 2, 4],
[3, 1, 4],
])('add(%i, %i) -> %i', (a, b, expected) => {
expect(a + b).toBe(expected);
});
```

feat: support array type cases in test `each` API

---

packages/core/src/runtime/runner/runtime.ts
packages/core/src/runtime/util.ts
packages/core/tests/runner/runtime.test.ts
packages/core/tests/runner/util.test.ts
tests/test-api/each.test.ts

```ts
it.each([
{ a: 1, b: 1, expected: 2 },
{ a: 1, b: 2, expected: 3 },
{ a: 2, b: 1, expected: 3 },
])('add($a, $b) -> $expected', ({ a, b, expected }) => {
expect(a + b).toBe(expected);
});
```

feat: support object type params in name template

---

packages/core/src/runtime/util.ts
packages/core/tests/runner/util.test.ts

fix: support printf-like string when format with object param

---

packages/core/src/runtime/api/index.ts
packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
tests/spy/stubEnv.test.ts

support `stubEnv` & `unstubAllEnvs` API.
- `stubEnv`: Changes the value of environmental variable on `process.env`.
- `unstubAllEnvs`: Restores all `process.env` values that were changed with `rstest.stubEnv`.
```ts
rstest.stubEnv('NODE_ENV', 'development');
// do something in development
// ...
rstest.unstubAllEnvs();
```

feat: support `stubEnv` & `unstubAllEnvs` API

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/runtime/api/index.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/config.ts
tests/spy/config.test.ts
tests/spy/fixtures/clearMocks.test.ts
tests/spy/fixtures/restoreMocks.test.ts
tests/spy/withImplementation.test.ts

- `clearMocks`: Automatically clear mock calls, instances, contexts and results before every test.
- `resetMocks`: Automatically reset mock state before every test.
- `restoreMocks`: Automatically restore mock state and implementation before every test.

feat: support `clearMocks` / `resetMocks` / `restoreMocks` configs

---

packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
scripts/dictionary.txt
tests/spy/stubGlobal.test.ts

- `stubGlobal`: Changes the value of global variable.
- `unstubAllGlobals`: Restores all global variables that were changed with `rstest.stubGlobal`.
```ts
rstest.stubGlobal('__test_flag__', true);
__test_flag__ // true
globalThis.__test_flag__  // true
```

feat: support `stubGlobal` & `unstubAllGlobals` API

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/types/config.ts

-  `unstubEnvs`: Restores all `process.env` values that were changed with `rstest.stubEnv` before every test.
-  `unstubGlobals`: Restores all global variables that were changed with `rstest.stubGlobal` before every test.

feat: support `unstubEnvs` & `unstubGlobals` configs

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/types/config.ts
tests/test-api/fixtures/retry.test.ts
tests/test-api/retry.test.ts

Support retry the test specific number of times if it fails via `retry` config.
```ts
retry: 2,
});
```

feat: support retry failed test

---

packages/core/src/runtime/api/utilities.ts
packages/core/src/types/mock.ts
pnpm-lock.yaml
tests/mock/package.json
tests/mock/tests/external.test.ts

This PR is used to initialize the mock API and does not include specific implementations.
- `rstest.doMock`: Mock a module, not hoisted.
- `rstest.unMock`: Removes module from the mocked registry.
- `rstest.doUnMock`: Removes module from the mocked registry, not hoisted.
- `rstest.importMock`: Imports a module with all of its properties (including nested properties) mocked.
- `rstest.importActual`: Returns the actual module instead of a mock, bypassing all checks on whether the module should receive a mock implementation or not.
- `rstest.resetModules`: Resets modules registry by clearing the cache of all modules.

feat: init mock API type declaration

---

packages/core/src/core/rsbuild.ts
packages/core/src/pool/index.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts
tests/build/fixtures/cssModules/index.test.ts
tests/build/fixtures/cssModules/rstest.config.ts
tests/build/fixtures/cssModules/src/env.d.ts
tests/build/fixtures/cssModules/src/index.module.css
tests/build/fixtures/cssModules/src/index.ts

`output.cssModules` configuration is used to setup css modules.
https://rsbuild.dev/config/output/css-modules

feat: support `output.cssModules` configuration

---

packages/core/src/core/rsbuild.ts
packages/core/src/pool/index.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts
packages/core/src/utils/helper.ts
tests/build/fixtures/tools/rspack/index.test.ts
tests/build/fixtures/tools/rspack/rstest.config.ts
tests/build/fixtures/tools/rspack/src/a.ts
tests/build/fixtures/tools/rspack/src/b.ts
tests/build/fixtures/tools/rspack/src/index.ts
tests/build/index.test.ts

support `tools.rspack` / `tools.swc` / `tools.bundlerChain` configs.
```ts
import path from 'node:path';
name: 'node',
tools: {
rspack: {
resolve: {
alias: {
'./a': path.join(__dirname, './src/b'),
},
},
},
},
});
```

feat: support tools rspack / swc / bundlerChain configs

---

packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/tests/runner/runtime.test.ts

* Removed the redundant `fails` method, as its functionality is now integrated into the refactored `it` method.

chore: merge runtime fails API

---

packages/core/src/reporter/summary.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/runtime/runner/task.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/test-api/concurrent.test.ts
tests/test-api/fixtures/concurrent.test.ts
tests/test-api/fixtures/concurrentIsolated.test.ts
tests/test-api/fixtures/concurrentLimit.test.ts
tests/test-api/fixtures/concurrentNested.test.ts

support run tests in parallel via `test.concurrent` API.
```ts
// The two tests marked with concurrent will be started in parallel
describe('suite', () => {
it('serial test', async () => { /* ... */ })
it.concurrent('concurrent test 1', async ({ expect }) => { /* ... */ })
it.concurrent('concurrent test 2', async ({ expect }) => { /* ... */ })
})
```

feat: support run tests in parallel

---

packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/describe/concurrent.test.ts
tests/describe/fixtures/concurrent.test.ts

If you use `.concurrent` on a suite, every test in it will be started in parallel.
```ts
// All tests within this suite will be started in parallel
describe.concurrent('suite', () => {
it('concurrent test 1', async () => { /* ... */ })
it('concurrent test 2', async () => { /* ... */ })
it('concurrent test 3', async () => { /* ... */ })
})
```

feat: support `describe.concurrent`

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/pool/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts
tests/test-api/concurrent.test.ts

- `maxConcurrency`: Maximum number of concurrent tests that are allowed to run at the same time in a test file (default: 5)

feat: support maxConcurrency option

---

packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/test-api/__snapshots__/concurrentContext.test.ts.snap
tests/test-api/concurrentContext.test.ts

Support get expect from test context. This API is useful for running snapshot and assertion tests concurrently because global expect cannot track them: 
```ts
it.concurrent('concurrent test 1', async ({ expect }) => {
await new Promise((resolve) => setTimeout(resolve, 100));
expect('hello world').toMatchSnapshot();
});
it.concurrent('concurrent test 2', async ({ expect }) => {
expect.assertions(2);
await new Promise((resolve) => setTimeout(resolve, 100));
expect(1 + 1).toBe(2);
expect(1 + 2).toBe(3);
});
```

feat: support get expect from test context

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/pool/index.ts
packages/core/src/reporter/index.ts
packages/core/src/runtime/worker/console.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/config.ts
packages/core/src/types/testSuite.ts
packages/core/src/types/worker.ts
tests/log/index.test.ts

support print console traces when calling console method via enabling `printConsoleTrace` configuration.

feat: support print console traces when calling console method

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/pool/index.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts
tests/log/index.test.ts

Support disabling console interception through the `disableConsoleIntercept` configuration. In this case, the `onConsoleLog` and `printConsoleTrace` configurations will not take effect.
```ts
disableConsoleIntercept: true,
});
```

feat: support disableConsoleIntercept

---

packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
tests/describe/chain.test.ts
tests/test-api/chain.test.ts

make all test API chainable (expect test.each & describe.each).
```ts
export type TestAPI = TestFn & {
fails: TestAPI;
concurrent: TestAPI;
only: TestAPI;
skip: TestAPI;
todo: TestAPI;
runIf: (condition: boolean) => TestAPI;
skipIf: (condition: boolean) => TestAPI;
each: TestEachFn;
};
export type DescribeAPI = DescribeFn & {
only: DescribeAPI;
skip: DescribeAPI;
runIf: (condition: boolean) => DescribeAPI;
skipIf: (condition: boolean) => DescribeAPI;
todo: DescribeFn;
concurrent: DescribeAPI;
each: DescribeEachFn;
};
```

feat: make all test API chainable

---

packages/core/src/core/rsbuild.ts
packages/core/src/reporter/index.ts
packages/core/src/runtime/api/expect.ts
packages/core/src/runtime/api/snapshot.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/runtime/worker/loadModule.ts
packages/core/src/types/testSuite.ts
packages/core/src/types/utils.ts
packages/core/src/types/worker.ts

Unify testPath & distPath usage in Rstest:
- testPath: the test file original path
- distPath: the test file output path

chore: unify testPath & distPath

---

packages/core/src/cli/commands.ts
packages/core/src/core/index.ts
packages/core/src/core/listTests.ts
packages/core/src/pool/forks.ts
packages/core/src/pool/index.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/core.ts
tests/list/index.test.ts

Support only list the test files via `--filesOnly`

feat: support only list the test files

---

packages/core/src/cli/commands.ts
packages/core/src/core/listTests.ts
packages/core/src/types/core.ts
tests/list/index.test.ts
tests/rstest.config.ts

Support print tests as JSON via `--json`.

feat: support print tests as JSON

---

packages/core/src/cli/commands.ts
packages/core/src/core/listTests.ts
packages/core/src/types/core.ts
tests/list/index.test.ts

support output test json to file via `--json <filePath>`
```bash
$ rstest list --json output.json
```

feat(list): support output test json to file

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/reporter/index.ts
packages/core/src/types/config.ts
tests/rstest.config.ts

- `slowTestThreshold`:  The number of milliseconds after which a test or suite is considered slow and reported as such in the results. Default: 300.
```bash
$ rstest run --slowTestThreshold 5000
```

feat: support slowTestThreshold option

---

packages/core/src/runtime/runner/runner.ts
tests/snapshot/fixtures/__snapshots__/obsolete.test.ts.snap
tests/snapshot/fixtures/__snapshots__/skip.test.ts.snap
tests/snapshot/fixtures/obsolete.test.ts
tests/snapshot/fixtures/skip.test.ts
tests/snapshot/obsolete.test.ts

should not mark snapshot obsolete when case skipped.
expect:
actual:

fix: should not mark snapshot obsolete when case skipped

---

packages/core/importMeta.d.ts
packages/core/package.json
packages/core/src/config.ts
packages/core/src/core/listTests.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts
packages/core/src/types/config.ts
packages/core/src/utils/testFiles.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
pnpm-lock.yaml
tests/in-source/fixtures/rslib.config.ts
tests/in-source/fixtures/rstest.config.ts
tests/in-source/fixtures/src/a.ts
tests/in-source/fixtures/src/index.ts
tests/in-source/fixtures/tsconfig.json
tests/in-source/index.test.ts
tests/package.json

Support run tests within source code, similar to [Rust's module tests](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-module-and-cfgtest).
When `includeSource` defined, Rstest will run all matched files with `import.meta.rstest` inside.
```diff
import { defineConfig } from '@rstest/core'
test: {
+    includeSource: ['src/**/*.{js,ts}'], 
},
})
```
```ts title=src/index.ts
export const sayHi = () => 'hi';
if (import.meta.rstest) {
const { it, expect } = import.meta.rstest;
it('should test source code correctly', () => {
expect(sayHi()).toBe('hi');
});
}
```
To get TypeScript support for `import.meta.rstest`, you should add `@rstest/core/importMeta` to your tsconfig.json:
```diff
{
"compilerOptions": {
"types": [
+ …
```

feat: in-source testing

---

packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
tests/test-api/chain.test.ts
tests/test-api/extend.test.ts

Init `test.extend` API, support use it to define your own test API with custom fixtures and reuse it anywhere.
Like [Playwright#test-extend](https://playwright.dev/docs/api/class-test#test-extend).
```ts
import { expect, test } from '@rstest/core';
const todos: number[] = [];
const myTest = test.extend<{
todos: number[];
}>({
todos: async (_, use) => {
todos.push(1, 2, 3);
await use(todos);
// cleanup after each test function
todos.length = 0;
},
});
myTest('add todo', ({ todos }) => {
expect(todos.length).toBe(3);
todos.push(4);
expect(todos.length).toBe(4);
});
```

feat: init `test.extend` API

---

packages/core/src/runtime/runner/runner.ts
tests/test-api/extend.test.ts

Test extend support define an option and provide a default value.
```ts
import { expect, test } from '@rstest/core';
const todos: number[] = [];
const myTest = test.extend<{
todos: number[];
archive: number[];
}>({
// Define an option and provide a default value.
archive: [],
// Define a fixture.
todos: async (_, use) => {
todos.push(1, 2, 3);
await use(todos);
// cleanup after each test function
todos.length = 0;
},
});
myTest('add archive', ({ archive }) => {
expect(archive.length).toBe(0);
archive.push(1, 2);
expect(archive.length).toBe(2);
});
```

fix(extend): support define an option

---

tests/test-api/edgeCase.test.ts

skip module not found case temporary, it should be fixed in rspack next version (1.3.12)
https://github.com/web-infra-dev/rstest/actions/runs/15152644316/job/42602104483?pr=209

test: skip module not found case temporary

---

packages/core/src/core/plugins/entry.ts
packages/core/src/core/plugins/ignoreResolveError.ts
packages/core/src/core/rsbuild.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap

- only enable TestFileWatchPlugin in watch mode.
- ignore `Module not found` warning. reference https://github.com/web-infra-dev/rspack/pull/10377

chore: optimize build config

---

packages/core/src/reporter/summary.ts
packages/core/src/runtime/runner/fixtures.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
packages/core/src/types/testSuite.ts
packages/core/src/utils/helper.ts
tests/test-api/extend.auto.test.ts
tests/test-api/extend.extend.test.ts
tests/test-api/extend.onDemand.test.ts

Support fixtures on-demand & `auto` option.
Rstest will setup fixtures  on-demand (only the ones needed by your test and nothing else). 
You can use `auto: true` to explicitly initialize a fixture, even if it's not being used in tests.
```ts
const myTest = test.extend<{
todos: number[];
archive: number[];
}>({
todos: [
async ({}, use) => {  // Will always be executed, although not used
todos.push(1, 2, 3);
await use(todos);
todos.length = 0;
},
{
auto: true,  
},
],
archive: async ({}, use) => {  // Will be executed when used
logs.push('init archive');
await use(archive);
archive.length = 0;
},
});
```

feat: support fixtures on-demand & `auto` option

---

pnpm-lock.yaml
website/package.json
website/rspress.config.ts

use Open Sans as the default font in Rstest website.
https://www.npmjs.com/package/rspress-plugin-font-open-sans

docs: use Open Sans as the default font

---

packages/core/src/core/rsbuild.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
tests/build/runtimeImport/a.js
tests/build/runtimeImport/b.ts
tests/build/runtimeImport/index.test.ts
tests/build/runtimeImport/package.json

should keep dynamic import expressions.
before:
after:

fix: should keep dynamic import expressions

---

website/docs/public/_redirects

Redirect rstest.dev to rstest.rs to ensure that users access the same domain name.
See: https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects

docs: redirect rstest.dev to rstest.rs

---

tests/test-api/edgeCase.test.ts

enable module not found case since rspack 1.3.12.
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.12
https://github.com/web-infra-dev/rspack/pull/10439

test: enable module not found case

---

packages/core/src/runtime/worker/index.ts
packages/core/src/runtime/worker/setup.ts

fix `--cpu-prof` not working in child_process. Gracefully handle SIGTERM to generate CPU profile.
https://github.com/nodejs/node/issues/55094

fix: `--cpu-prof` not working in child_process

---

website/docs/en/guide/_meta.json
website/docs/en/guide/advanced/_meta.json
website/docs/en/guide/advanced/profiling.mdx
website/docs/zh/guide/_meta.json
website/docs/zh/guide/advanced/_meta.json
website/docs/zh/guide/advanced/profiling.mdx

[Rsdoctor](https://rsdoctor.rs/) is a build analysis tool that can visually display the compilation time of each loaders and plugins.
When you need to debug Rstest's build outputs or build processes, you can use Rsdoctor for troubleshooting.

docs: add `Rsdoctor` guide

---

README.md
packages/core/README.md
website/README.md
website/docs/en/guide/start/index.mdx
website/docs/zh/guide/start/index.mdx
website/rspress.config.ts
website/theme/components/Hero.tsx
website/theme/components/RsbuildDocBadge.tsx

Update URLs to use the new `.rs` domain.

docs: update URLs to use the new domain

---

packages/core/src/core/listTests.ts
packages/core/src/reporter/index.ts
packages/core/src/reporter/summary.ts
packages/core/src/utils/error.ts
packages/core/src/utils/testFiles.ts
tests/setup/index.test.ts

- update snapshot prefix pointer
- shorten the error trace path
- ignore vitest/snapshot in trace
before:
after:

enhance: optimize snapshot output

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/pool/index.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts

The `testEnvironment` configuration can be used to specify the environment to use for testing.
```ts
testEnvironment: 'node',
});
```

feat: init testEnvironment configuration

---

scripts/dictionary.txt
website/docs/en/guide/advanced/profiling.mdx
website/docs/zh/guide/advanced/profiling.mdx

[Samply](https://github.com/mstange/samply) supports performance analysis for both Rstest main process and test process simultaneously.

docs: add Samply profiling guide

---

packages/core/src/core/listTests.ts

fix: only print failed files when test error

---

tests/build/index.test.ts
tests/cli/index.test.ts
tests/externals/index.test.ts
tests/filter/default.test.ts
tests/filter/regex.test.ts
tests/filter/testNamePattern.test.ts
tests/globals/index.test.ts
tests/in-source/index.test.ts
tests/jsdom/handledError.test.ts
tests/jsdom/index.test.ts
tests/list/index.test.ts
tests/list/json.test.ts
tests/noTests/index.test.ts
tests/scripts/index.ts
tests/setup/index.test.ts
tests/snapshot/obsolete.test.ts
tests/spy/config.test.ts
tests/ssr/index.test.ts
tests/test-api/concurrentLimit.test.ts
tests/test-api/edgeCase.test.ts
tests/test-api/retry.test.ts

support throw error logs when test failed:

test(e2e): support throw error logs when test failed

---

packages/core/src/runtime/worker/index.ts
tests/externals/interop.test.ts

fix `lodash` import error in node test environment. should interopDefault in node test environment by default.

fix: should interopDefault in node test environment by default

---

website/docs/en/config/test/_meta.json
website/docs/en/config/test/setupFiles.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/setupFiles.mdx

docs: add `setupFiles` configuration.
`setupFiles` is a list of paths to modules that run some code to configure or set up the testing environment, they will be run before each test file.

docs: add `setupFiles` configuration

---

packages/core/rslib.config.ts

remove licensePlugin in rslib watch mode, temporarily fix licensePlugin watch error.

chore: remvoe licensePlugin  in rslib watch mode

---

website/docs/en/api/rstest/_meta.json
website/docs/en/config/_meta.json
website/docs/en/config/build/plugins.mdx
website/docs/zh/api/rstest/_meta.json
website/docs/zh/config/_meta.json
website/docs/zh/config/build/plugins.mdx

Rstest and Rsbuild share the same plugin system, so you can use Rsbuild plugins in Rstest.
https://rsbuild.dev/config/plugins

docs: add `plugins` configuration

---

packages/core/src/core/rsbuild.ts
packages/core/src/types/config.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
tests/jsdom/fixtures/rstest.externals.config.ts
tests/jsdom/index.test.ts
website/docs/en/config/build/output.mdx
website/docs/zh/config/build/output.mdx

`externals` can be prevent some `import` dependencies from being packed into bundles in your code, and instead Rstest will `import` them at runtime.
```ts title="rstest.config.ts"
output: {
externals: ['react'],
},
});
```

feat: support `externals` configuration

---

packages/core/src/runtime/worker/index.ts
tests/runner/test/processExit.test.ts

Allow call `process.exit` in user land code, which will turn to be an `Error` instead of terminating the process.

feat: handle process.exit in pool

---

packages/core/src/core/plugins/mockRuntime.ts
pnpm-lock.yaml
tests/mock/tests/defaultInterop.test.ts
tests/mock/tests/resetModules.test.ts
tests/package.json
tests/rstest.config.ts

`resetModules` should not clear mocked modules.

fix(mock): resetModules should not clear mock

---

biome.json
packages/core/rslib.config.ts
packages/core/src/core/plugins/css-filter/index.ts
packages/core/src/core/plugins/css-filter/loader.ts
packages/core/src/core/rsbuild.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
tests/jsdom/css.test.ts
tests/jsdom/fixtures/rsbuild.config.ts
tests/jsdom/fixtures/src/App.css
tests/jsdom/fixtures/src/App.module.css
tests/jsdom/fixtures/src/App.tsx
tests/jsdom/fixtures/test/css.test.tsx

When CSS does not need to be emitted, pre-set the CSS content to empty (except for CSS modules) to reduce time costs in less-loader / sass-loader / css-loader.

perf: add pre-filter for css

---

packages/core/src/cli/commands.ts
packages/core/src/config.ts
packages/core/src/pool/index.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/config.ts
packages/core/src/types/worker.ts
website/docs/en/config/test/_meta.json
website/docs/en/config/test/hookTimeout.mdx
website/docs/en/guide/basic/cli.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/hookTimeout.mdx
website/docs/zh/guide/basic/cli.mdx

support `hookTimeout` configuration. update default hookTimeout value from 5_000 to 10_000 (Consistent with vitest).
close: https://github.com/web-infra-dev/rstest/issues/361

feat: support hookTimeout

---

packages/core/src/core/rsbuild.ts

Disable some of rsbuild's default devMiddlewares that are not used in rstest.
https://rsbuild.rs/config/

perf: disable some of rsbuild's default devMiddlewares

---

package.json

fix `pnpm run check-dependency-version` error when commit.
`check-dependency-version` 5.0.1 update command from v12 to v13 which will throw an error with excessArguments
https://github.com/web-infra-dev/rslib/pull/1107

chore: correct check-dependency-version script

---

package.json
packages/core/src/core/rsbuild.ts
packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
pnpm-lock.yaml
tests/tsconfig.json
tests/vue/fixtures/package.json
tests/vue/fixtures/rsbuild.config.ts
tests/vue/fixtures/rstest.config.ts
tests/vue/fixtures/src/App.jsx
tests/vue/fixtures/src/App.tsx
tests/vue/fixtures/src/App.vue
tests/vue/fixtures/src/index.css
tests/vue/fixtures/src/index.js
tests/vue/fixtures/test/index.test.ts
tests/vue/fixtures/test/jsx.test.ts
tests/vue/fixtures/tsconfig.json
tests/vue/index.test.ts

Fix unexpected resolution of vue to `vue.cjs.prod.js` when `NODE_ENV=test`.
By default, Rspack treats `NODE_ENV=test` as `production` in some cases (e.g., `conditionNames`). However, frameworks like Vue and React (and tools like Vitest) expect test to follow development-mode behavior.
https://github.com/web-infra-dev/rspack/blob/8671bc16eb74961dcd98a5bb03eae4efce936914/packages/rspack/src/config/defaults.ts#L1069

fix: unexpected resolution of vue to `vue.cjs.prod.js` when `NODE_ENV=test`

---

packages/core/src/cli/commands.ts
website/docs/en/config/test/include.mdx
website/docs/en/guide/basic/_meta.json
website/docs/en/guide/basic/test-filter.mdx
website/docs/zh/config/test/include.mdx
website/docs/zh/guide/basic/_meta.json
website/docs/zh/guide/basic/test-filter.mdx

- support`--include` CLI option to match test files. 
- add `test filter` chapter
Match test files in the `test/a` directory:
```bash
rstest --include test/a/*.test.ts
```
Match test files in `test/a` or `test/b` directories:
```bash
rstest --include test/a/*.test.ts --include test/b/*.test.ts
```
close: https://github.com/web-infra-dev/rstest/issues/383

feat: support `--include` CLI option to match test files

---

packages/core/src/core/rsbuild.ts
pnpm-lock.yaml
tests/externals/bundle.test.ts
tests/externals/fixtures/bundle.test.ts
tests/externals/fixtures/rstest.bundle.config.ts
tests/externals/fixtures/test-bundle/index.ts
tests/externals/fixtures/test-bundle/package.json
tests/externals/fixtures/test-pkg/env.d.ts
tests/externals/fixtures/test-pkg/testBundle.ts
tests/vue/sfc.test.ts
website/docs/en/config/build/output.mdx
website/docs/zh/config/build/output.mdx

In the Node.js test environment, all packages in `node_modules` are externalized by default.
If you want all dependencies to be bundled, you can configure it through the following configuration:
```ts title="rstest.config.ts"
tools: {
rspack: (config) => {
config.externals = [];
},
},
});
```

feat: support bundle `node_modules` in node environment

---

packages/core/src/cli/prepare.ts
packages/core/src/core/rsbuild.ts
tests/basic/test/index.test.ts
tests/cli/fixtures/flag.config.ts
tests/cli/index.test.ts
website/docs/en/config/test/includeSource.mdx
website/docs/en/guide/basic/configure-rstest.mdx
website/docs/zh/config/test/includeSource.mdx
website/docs/zh/guide/basic/configure-rstest.mdx

`process.env.RSTEST` can be used to determine if it is an rstest environment.
```ts
if (process.env.RSTEST) {
// do something...
}
```

feat: add `RSTEST` flag

---

pnpm-lock.yaml
website/package.json
website/rspress.config.ts
website/theme/components/Hero.tsx
website/theme/components/Overview.tsx
website/theme/components/RsbuildDocBadge.tsx
website/theme/components/Step.tsx
website/theme/components/ToolStack.tsx
website/theme/components/utils.ts
website/theme/index.tsx

Update Rspress to 2.0.0-beta.22 and use the new package name.
https://github.com/web-infra-dev/rspress/releases

chore(deps): update Rspress to 2.0.0-beta.22

---

packages/core/src/core/plugins/basic.ts
packages/core/src/core/plugins/external.ts
packages/core/src/core/rsbuild.ts
tests/snapshot/file.test.ts
website/docs/en/api/test-api/expect.mdx
website/docs/zh/api/test-api/expect.mdx

chore: extract rsbuild / rspack config modify into rsbuild plugin:
- `pluginBasic` Plugin: handle core `rsbuild` configurations, including environment setup, output configuration, and optimization settings. This modularizes previously inline configurations.
- `pluginExternal` Plugin: manage external dependencies, including automatic handling of Node.js built-ins and `node_modules`.

chore: extract rsbuild / rspack config modify into rsbuild plugin

---

packages/core/src/utils/error.ts
tests/scripts/index.ts
tests/test-api/edgeCase.test.ts
tests/test-api/fixtures/moduleNotFound.codeFrame.test.ts

should show `module not found` error codeFrame correctly.
before:
after:

fix: should show `module not found` error codeFrame correctly

---

packages/core/src/config.ts
packages/core/src/core/context.ts
packages/core/src/reporter/githubActions.ts
packages/core/src/utils/error.ts
tests/reporter/fixtures/githubActions.test.ts
tests/reporter/githubActions.test.ts
tests/reporter/index.test.ts
tests/rstest.config.ts
website/docs/en/config/test/reporters.mdx
website/docs/zh/config/test/reporters.mdx

Github Actions Reporter will output [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) to provide annotations for test failures.
When no reporter is manually set, Rstest automatically enables this reporter when it detects a GitHub Actions environment (`process.env.GITHUB_ACTIONS` is `'true'`).
You can also manually enable this reporter:
via `CLI`:
```bash
npx rstest --reporter=github-actions
```
via `rstest.config.ts`:
```ts
reporters: ['github-actions']
});
```

feat: support Github Actions Reporter

---

packages/core/LICENSE
packages/core/package.json
packages/core/rslib.config.ts
pnpm-lock.yaml
scripts/dictionary.txt

Prebundle runtime dependencies to speed up runtime.
before:
after:

perf: prebundle runtime dependencies

---

website/docs/en/api/rstest/fakeTimers.mdx
website/docs/zh/api/rstest/fakeTimers.mdx

fix `@sinonjs/fake-timers` link.

docs: fix `@sinonjs/fake-timers` link

---

.github/workflows/release.yml
packages/core/package.json

Enable OIDC publishing to make it easier and more secure to publish npm packages from CI.
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
- https://docs.npmjs.com/trusted-publishers

chore(workflow): enable npm trusted publishing

---

packages/core/rslib.config.ts
packages/core/src/runtime/api/poll.ts
packages/core/src/runtime/runner/task.ts
packages/core/src/runtime/util.ts
packages/core/src/runtime/worker/index.ts
tests/fakeTimers/index.test.ts

shim `require` in rstest bundle. fix `require is not defined` error when fake timers.

fix: shim `require` in rstest bundle

---

website/docs/en/api/test-api/describe.mdx
website/docs/zh/api/test-api/describe.mdx

The `skip` tag is only used to skip test cases, and the code inside the describe block will still be executed.
```ts
describe.skip('a', () => {
console.log('will run');
test('b', () => {
console.log('will not run');
expect(0).toBe(0);
});
});
```

docs: add note for `describe.skip`

---

packages/core/src/core/plugins/inspect.ts
packages/core/src/core/rsbuild.ts

use `inline-source-map` when debugger.
fix https://github.com/web-infra-dev/rstest/issues/409

fix: use `inline-source-map` when debugger

---

packages/core/src/core/cliShortcuts.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts

support rerun only failed tests via `f` shortcut.

feat: support rerun failed tests via `f` shortcut

---

packages/core/src/core/cliShortcuts.ts
packages/core/src/core/runTests.ts

support trigger shortcut without `enter`, use `keypress` instead of `line` event.

enhance: support trigger shortcut without `enter` event

---

packages/core/src/core/plugins/entry.ts
packages/core/src/core/runTests.ts

only rerun failed snapshot test files when update snapshots.

enhance: only rerun failed snapshot test files when update snapshots

---

packages/core/bin/rstest.js
packages/core/package.json
packages/core/rslib.config.ts
packages/core/src/index.ts
packages/core/src/node.ts
tests/reporter/rstest.customReporterConfig.ts

Remove `node` exports, only exports all `types` and `exports`  from main entry.
Restructures the public API surface of the `@rstest/core` package to simplify imports and clarify module boundaries. The main entry point has been consolidated to `index.ts`, and types and exports have been unified to reduce confusion for consumers. 
```diff
import type {
Reporter,
TestFileInfo,
TestFileResult,
TestResult,
- } from '@rstest/core/node';
+ } from '@rstest/core';
```

refactor!: remove `node` exports

---

packages/core/src/cli/commands.ts
website/docs/en/guide/basic/cli.mdx
website/docs/zh/guide/basic/cli.mdx

Update CLI command and documentation to support `-w` as shorthand for `--watch` flag.

feat(cli): add short option -w for watch mode

---

e2e/lifecycle/fixtures/onTestFinished.failed.test.ts
e2e/lifecycle/fixtures/onTestFinished.outside.test.ts
e2e/lifecycle/fixtures/onTestFinished.test.ts
e2e/lifecycle/onTestFinished.test.ts
packages/core/src/runtime/api/public.ts
packages/core/src/runtime/runner/index.ts
packages/core/src/runtime/runner/runner.ts
packages/core/src/runtime/runner/runtime.ts
packages/core/src/types/api.ts
website/docs/en/api/test-api/hooks.mdx
website/docs/zh/api/test-api/hooks.mdx

`onTestFinished` hook will called after the test has finished running **whatever the test result is**. This can be used to perform cleanup actions. This hook will be called after `afterEach`.
```ts
import { onTestFinished, test } from '@rstest/core';
test('test server', () => {
const server = startServer();
// Register a cleanup function to close the server after the test
onTestFinished(() => server.close());
server.listen(3000, () => {
console.log('Server is running on port 3000');
});
});
```

feat: support `onTestFinished` hook

---

e2e/watch/index.test.ts
e2e/watch/shortcuts.test.ts
packages/core/src/core/rsbuild.ts
packages/core/src/core/runTests.ts

simplify `isFirstRun` check when run tests.

chore: use `isFirstCompile` instead of `isFirstRun`

---

e2e/projects/fixtures/packages/node/__mocks__/fs.js
e2e/projects/fixtures/packages/node/src/readSomeFile.ts
e2e/projects/fixtures/packages/node/test/mockFs.test.ts
packages/core/src/core/plugins/basic.ts

fix `manualMockRoot` in projects, use `project.rootPath` instead of `context.rootPath`.

fix: manualMockRoot in projects

---

examples/react/package.json
examples/react/rstest.config.ts
examples/react/rstest.setup.ts
examples/react/test/App.test.tsx
examples/react/test/tsconfig.json
pnpm-lock.yaml

update react example with `@testing-library/jest-dom`

chore: update react example with `@testing-library/jest-dom`

---

e2e/projects/filter.test.ts
packages/core/src/cli/commands.ts
packages/core/src/cli/init.ts
packages/core/src/utils/testFiles.ts
packages/core/tests/utils/testFiles.test.ts
website/docs/en/config/test/name.mdx
website/docs/en/config/test/projects.mdx
website/docs/en/guide/basic/cli.mdx
website/docs/en/guide/basic/test-filter.mdx
website/docs/zh/config/test/name.mdx
website/docs/zh/config/test/projects.mdx
website/docs/zh/guide/basic/cli.mdx
website/docs/zh/guide/basic/test-filter.mdx

Support filter projects via `--project` option.
For example, to match projects whose [name](/config/test/name) is `@test/a` or `@test/b`:
```bash
rstest --project '@test/a' --project '@test/b'
```
You can also use wildcards to match project names:
```bash
rstest --project '@test/*'
```
You can exclude certain projects by negation:
```bash
rstest --project '!@test/a'
```

feat: support filter projects via `--project` option

---

e2e/projects/fixtures/rstest.inline.config.ts
e2e/projects/inline.test.ts
packages/core/src/cli/init.ts
packages/core/src/core/rstest.ts
packages/core/src/types/config.ts
packages/core/src/types/core.ts
website/docs/en/config/test/projects.mdx
website/docs/zh/config/test/projects.mdx

Supports configuring projects inline in the `projects` field. This lets you define multiple test projects in a single root without creating separate config files for each test project.
```ts name='rstest.config.ts'
projects: [
// inline project configs
{
name: 'node',
include: ['tests/node/**/*.{test,spec}.{js,cjs,mjs,ts,tsx}'],
},
{
name: 'react',
include: ['tests/react/**/*.{test,spec}.{js,cjs,mjs,ts,tsx}'],
testEnvironment: 'jsdom',
},
],
});
```

feat: support inline project config

---

packages/core/src/utils/error.ts

Rstest will ignore some stack traces that are not related to the user's source code, such as `webpack/runtime` and `@rstest/core` by default.
Support printing the full error stack in debug mode, making the stack trace more verbose and easier to analyze.

chore: support print full error stack in debug mode

---

e2e/reporter/fixtures/junit.test.ts
e2e/reporter/junit.test.ts
packages/core/LICENSE.md
packages/core/package.json
packages/core/src/core/rstest.ts
packages/core/src/reporter/junit.ts
packages/core/src/utils/error.ts
packages/core/tests/reporter/junit.test.ts
pnpm-lock.yaml
scripts/dictionary.txt
website/docs/en/config/test/reporters.mdx
website/docs/zh/config/test/reporters.mdx

The JUnit reporter supports outputting test reports in JUnit XML format, making it easy to integrate with CI/CD.
```ts title="rstest.config.ts"
reporters: [['junit', { outputPath: './junit.xml' }]],
});
```

feat: add JUnit reporter

---

packages/core/package.json
pnpm-lock.yaml

Node 18 still needs support.
Reverts web-infra-dev/rstest#536

Revert "chore(deps): update dependency tinypool to v2"

---

website/docs/en/guide/start/_meta.json
website/docs/en/guide/start/features.mdx
website/docs/zh/guide/start/_meta.json
website/docs/zh/guide/start/features.mdx

List the key features supported by Rstest.

docs: add features chapter

---

pnpm-lock.yaml
website/package.json
website/rspress.config.ts
website/theme/index.tsx

~~use Algolia search instead of local search, need to wait for seat to be approved first.~~

docs: use Algolia search

---

packages/core/globals.d.ts

add `rs` to global API.
```diff
- import { rs } from '@rstest/core';
import { sum } from './sum';
rs.mock('./sum', () => {
return {
sum: (a: number, b: number) => a + b + 100,
};
});
```

fix: add `rs` to global API

---

e2e/runner/test/fixtures/globals.test.ts
e2e/runner/test/fixtures/test-rstest-globals/index.js
e2e/runner/test/fixtures/test-rstest-globals/package.json
e2e/runner/test/runner.test.ts
packages/core/src/runtime/worker/index.ts
pnpm-lock.yaml

support use rstest global APIs in external modules.

fix: support use rstest global APIs in external modules

---

e2e/projects/coverage.test.ts
e2e/test-coverage/index.test.ts
packages/coverage-istanbul/package.json
pnpm-lock.yaml

Fix coverage plugin's exclusion config on Windows, reenable https://github.com/web-infra-dev/rstest/blob/4aed867108285a08e16246cb292b1ead68dfbe7e/e2e/projects/coverage.test.ts#L10

fix(coverage): fix coverage exclusion on windows

---

website/docs/en/config/test/_meta.json
website/docs/en/config/test/coverage.mdx
website/docs/zh/config/test/_meta.json
website/docs/zh/config/test/coverage.mdx
website/theme/components/ConfigOverview.tsx

docs: add `coverage` configuration

---

e2e/test-coverage/fixtures/rstest.thresholds.config.ts
e2e/test-coverage/fixtures/test/string.test.ts
e2e/test-coverage/index.test.ts
packages/core/src/coverage/checkThresholds.ts
packages/core/src/types/coverage.ts
website/docs/en/config/test/coverage.mdx
website/docs/zh/config/test/coverage.mdx

Allow set coverage thresholds as negative number. Thresholds specified as a negative number represent the maximum number of uncovered entities allowed.
```ts title='rstest.config.ts'
coverage: {
enabled: true,
thresholds: {
lines: -10,
},
},
});
```
```bash
Error: Uncovered lines 20 exceeds maximum global threshold allowed 10
```

feat: allow set coverage thresholds as negative number

---

e2e/test-coverage/fixtures/rstest.perFileThresholds.config.ts
e2e/test-coverage/thresholds.test.ts
packages/core/src/coverage/checkThresholds.ts
packages/core/src/coverage/generate.ts
packages/core/src/runtime/worker/index.ts
packages/core/src/types/coverage.ts
website/docs/en/config/test/coverage.mdx
website/docs/zh/config/test/coverage.mdx

support check coverage threshold for per file.
```ts title='rstest.config.ts'
coverage: {
enabled: true,
thresholds: {
'src/**': {
statements: 90,
perFile: true,
},
},
},
});
```

feat: support check coverage threshold for per file

---

e2e/projects/coverage.test.ts
e2e/projects/fixtures/packages/client/src/App1.tsx
e2e/projects/fixtures/rstest.coverage.config.ts
e2e/projects/fixtures/rstest.coverage.include.config.ts
packages/core/src/core/runTests.ts
packages/core/src/coverage/generate.ts
packages/core/src/types/coverage.ts
packages/coverage-istanbul/src/plugin.ts
packages/coverage-istanbul/src/provider.ts

Scans the included files based on each project's root directory, so the pattern `'/src/**/*.{js,jsx,ts,tsx}'` can match:
- `/root/project1/src/index.ts`
- `/root/project2/src/index.ts`

feat: `coverage.includes` works in projects

---

packages/core/package.json
packages/coverage-istanbul/package.json

* feat!: merge `exclude` values by default by @9aoy in https://github.com/web-infra-dev/rstest/pull/588
* feat: support `coverage.include` by @9aoy in https://github.com/web-infra-dev/rstest/pull/585
* feat: `coverage.includes` works in projects by @9aoy in https://github.com/web-infra-dev/rstest/pull/593
* feat: support use `<rootDir>` in path-based configuration settings by @9aoy in https://github.com/web-infra-dev/rstest/pull/583
* feat: support checking coverage threshold for glob files by @9aoy in https://github.com/web-infra-dev/rstest/pull/589
* feat: support check coverage threshold for per file by @9aoy in https://github.com/web-infra-dev/rstest/pull/590
* feat: `stubEnv` support `import.meta.env` by @9aoy in https://github.com/web-infra-dev/rstest/pull/594
* fix: should not …

release: 0.5.0

---

e2e/test-coverage/fixtures/rstest.globThresholds.config.ts
e2e/test-coverage/fixtures/rstest.include.config.ts
e2e/test-coverage/fixtures/rstest.perFileThresholds.config.ts
e2e/test-coverage/fixtures/rstest.skipFull.config.ts
e2e/test-coverage/fixtures/rstest.thresholds.config.ts

fix unstable coverage tests due to clean coverage directory conflict.

test: fix unstable coverage tests

---

website/docs/en/guide/migration/jest.mdx
website/docs/zh/guide/migration/jest.mdx

docs: update jest api alternative

---

website/docs/en/api/test-api/hooks.mdx
website/docs/en/guide/migration/jest.mdx
website/docs/zh/api/test-api/hooks.mdx
website/docs/zh/guide/migration/jest.mdx

The return functions of the `beforeEach` and `beforeAll` hooks in Rstest are used to perform cleaning work after testing.

docs: introduce beforeEach / beforeAll returns
